/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.latihangui2.view;

import javax.swing.JOptionPane;

/**
 *
 * @author amxyfa
 */
public class Mainmenu extends javax.swing.JFrame {

    /**
     * Creates new form Mainmenu
     */
    public Mainmenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnHome = new javax.swing.JLabel();
        btnCountries = new javax.swing.JLabel();
        btnVisit = new javax.swing.JLabel();
        btnAbout = new javax.swing.JLabel();
        btnSignout = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        visit = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtFullname = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtFrom = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        cmbTo = new javax.swing.JComboBox<>();
        btnDone = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOutput = new javax.swing.JTextArea();
        jSeparator3 = new javax.swing.JSeparator();
        countries = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        denmark = new javax.swing.JButton();
        norway = new javax.swing.JButton();
        sweden = new javax.swing.JButton();
        iceland = new javax.swing.JButton();
        finland = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuPanel.setBackground(new java.awt.Color(25, 42, 86));

        menu.setBackground(new java.awt.Color(245, 246, 250));

        jLabel1.setFont(new java.awt.Font("Gravity", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(25, 42, 86));
        jLabel1.setText("SCANDINAVIA");

        btnHome.setFont(new java.awt.Font("Gravity", 1, 14)); // NOI18N
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/latihangui2/icon/icons8-home-filled-30.png"))); // NOI18N
        btnHome.setText("Home");
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });

        btnCountries.setFont(new java.awt.Font("Gravity", 1, 14)); // NOI18N
        btnCountries.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/latihangui2/icon/icons8-europe-filled-30.png"))); // NOI18N
        btnCountries.setText("Countries");
        btnCountries.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCountries.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCountries.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCountriesMouseClicked(evt);
            }
        });

        btnVisit.setFont(new java.awt.Font("Gravity", 1, 14)); // NOI18N
        btnVisit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/latihangui2/icon/icons8-paper-plane-filled-30.png"))); // NOI18N
        btnVisit.setText(" Visit Us");
        btnVisit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVisit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVisit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVisitMouseClicked(evt);
            }
        });

        btnAbout.setFont(new java.awt.Font("Gravity", 1, 14)); // NOI18N
        btnAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/latihangui2/icon/icons8-user-menu-male-filled-30.png"))); // NOI18N
        btnAbout.setText("About");
        btnAbout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAbout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAboutMouseClicked(evt);
            }
        });

        btnSignout.setBackground(new java.awt.Color(153, 0, 0));
        btnSignout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSignout.setForeground(new java.awt.Color(255, 255, 255));
        btnSignout.setText("Sign Out");
        btnSignout.setBorder(null);
        btnSignout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignoutActionPerformed(evt);
            }
        });

        btnProfile.setBackground(new java.awt.Color(153, 0, 0));
        btnProfile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnProfile.setText("Profile");
        btnProfile.setBorder(null);
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSignout, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAbout)
                .addGap(36, 36, 36)
                .addComponent(btnVisit)
                .addGap(29, 29, 29)
                .addComponent(btnCountries)
                .addGap(29, 29, 29)
                .addComponent(btnHome)
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(42, 42, 42))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addComponent(btnAbout)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(menuLayout.createSequentialGroup()
                                .addComponent(btnSignout, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(menuLayout.createSequentialGroup()
                                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCountries)
                                    .addComponent(btnHome)
                                    .addComponent(btnVisit))
                                .addGap(0, 3, Short.MAX_VALUE)))
                        .addContainerGap())))
        );

        mainPanel.setBackground(new java.awt.Color(25, 42, 86));
        mainPanel.setLayout(new java.awt.CardLayout());

        home.setBackground(new java.awt.Color(25, 42, 86));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Welcome To");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("The Happiest Countries");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("In The World");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/latihangui2/icon/icons8-happy-filled-65.png"))); // NOI18N

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addContainerGap(308, Short.MAX_VALUE))
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        mainPanel.add(home, "card2");

        visit.setBackground(new java.awt.Color(25, 42, 86));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Fullname");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("From");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("To");

        txtFullname.setBackground(new java.awt.Color(25, 42, 86));
        txtFullname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtFullname.setForeground(new java.awt.Color(255, 255, 255));
        txtFullname.setBorder(null);

        txtFrom.setBackground(new java.awt.Color(25, 42, 86));
        txtFrom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtFrom.setForeground(new java.awt.Color(255, 255, 255));
        txtFrom.setBorder(null);

        cmbTo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbTo.setForeground(new java.awt.Color(51, 51, 51));
        cmbTo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Denmark", "Norway", "Sweden", "Finland", "Iceland" }));

        btnDone.setBackground(new java.awt.Color(255, 255, 255));
        btnDone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDone.setForeground(new java.awt.Color(51, 51, 51));
        btnDone.setText("Done");
        btnDone.setBorder(null);
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });

        txtOutput.setBackground(new java.awt.Color(25, 42, 86));
        txtOutput.setColumns(20);
        txtOutput.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtOutput.setForeground(new java.awt.Color(255, 255, 255));
        txtOutput.setRows(5);
        jScrollPane1.setViewportView(txtOutput);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout visitLayout = new javax.swing.GroupLayout(visit);
        visit.setLayout(visitLayout);
        visitLayout.setHorizontalGroup(
            visitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(visitLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(visitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(visitLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(cmbTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnDone, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(visitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel11)
                        .addComponent(jLabel12)
                        .addComponent(txtFullname, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                        .addComponent(jSeparator1)
                        .addComponent(txtFrom)
                        .addComponent(jSeparator2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        visitLayout.setVerticalGroup(
            visitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(visitLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(visitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(visitLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(visitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(cmbTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(btnDone, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator3))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        mainPanel.add(visit, "card2");

        countries.setBackground(new java.awt.Color(25, 42, 86));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/latihangui2/icon/denmark.png"))); // NOI18N
        jLabel6.setText("Denmark");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/latihangui2/icon/norway.png"))); // NOI18N
        jLabel7.setText("Norway");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/latihangui2/icon/sweden.png"))); // NOI18N
        jLabel8.setText("Sweden");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/latihangui2/icon/finland.png"))); // NOI18N
        jLabel9.setText("Finland");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/latihangui2/icon/iceland.png"))); // NOI18N
        jLabel10.setText("Iceland");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        denmark.setBackground(new java.awt.Color(255, 255, 255));
        denmark.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        denmark.setText("info");
        denmark.setBorder(null);
        denmark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                denmarkActionPerformed(evt);
            }
        });

        norway.setBackground(new java.awt.Color(255, 255, 255));
        norway.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        norway.setText("info");
        norway.setBorder(null);
        norway.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                norwayActionPerformed(evt);
            }
        });

        sweden.setBackground(new java.awt.Color(255, 255, 255));
        sweden.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sweden.setText("info");
        sweden.setBorder(null);
        sweden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                swedenActionPerformed(evt);
            }
        });

        iceland.setBackground(new java.awt.Color(255, 255, 255));
        iceland.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        iceland.setText("info");
        iceland.setBorder(null);
        iceland.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                icelandActionPerformed(evt);
            }
        });

        finland.setBackground(new java.awt.Color(255, 255, 255));
        finland.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        finland.setText("info");
        finland.setBorder(null);
        finland.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finlandActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout countriesLayout = new javax.swing.GroupLayout(countries);
        countries.setLayout(countriesLayout);
        countriesLayout.setHorizontalGroup(
            countriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(countriesLayout.createSequentialGroup()
                .addGroup(countriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(countriesLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel9)
                        .addGap(84, 84, 84)
                        .addComponent(jLabel10))
                    .addGroup(countriesLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel6)
                        .addGap(64, 64, 64)
                        .addComponent(jLabel7)
                        .addGap(63, 63, 63)
                        .addComponent(jLabel8))
                    .addGroup(countriesLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(denmark, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114)
                        .addComponent(norway, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126)
                        .addComponent(sweden, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(97, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, countriesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(finland, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149)
                .addComponent(iceland, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202))
        );
        countriesLayout.setVerticalGroup(
            countriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(countriesLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(countriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(countriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(denmark)
                    .addComponent(norway)
                    .addComponent(sweden))
                .addGap(32, 32, 32)
                .addGroup(countriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(countriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iceland)
                    .addComponent(finland))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        mainPanel.add(countries, "card2");

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseClicked
        // TODO add your handling code here:
        About n = new About();
        n.setVisible(true);
    }//GEN-LAST:event_btnAboutMouseClicked

    private void btnVisitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVisitMouseClicked
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        //add panel
        mainPanel.add(visit);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnVisitMouseClicked

    private void btnCountriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCountriesMouseClicked
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        //add panel
        mainPanel.add(countries);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnCountriesMouseClicked

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        //add panel
        mainPanel.add(home);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        // TODO add your handling code here:
         String fullname, to = "";
        String from;
        
        fullname  = txtFullname.getText();
        from = txtFrom.getText();
        
        if (cmbTo.getSelectedItem()== "Denmark"){
            to = "Denmark";
        } else if (cmbTo.getSelectedItem()== "Norway"){
            to = "Norway";
        } else if (cmbTo.getSelectedItem()== "Sweden"){
            to = "Sweden";
        } else if (cmbTo.getSelectedItem()== "Finland"){
            to = "Finland";
        } else if (cmbTo.getSelectedItem()== "Iceland"){
            to = "Iceland";
        }
        
        txtOutput.setText("Fullname : "+ fullname +
                "\nFrom : " + from + 
                "\nTo : " + to);
    }//GEN-LAST:event_btnDoneActionPerformed

    private void btnSignoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignoutActionPerformed
        // TODO add your handling code here:
        dispose();
        Login n = new Login();
        n.setVisible(true);
    }//GEN-LAST:event_btnSignoutActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
        Profile n = new Profile();
        n.setVisible(true);
    }//GEN-LAST:event_btnProfileActionPerformed

    private void denmarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_denmarkActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Choosed denmark");
        
    }//GEN-LAST:event_denmarkActionPerformed

    private void norwayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_norwayActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Choosed Norway");
    }//GEN-LAST:event_norwayActionPerformed

    private void swedenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_swedenActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Choosed Sweden");
    }//GEN-LAST:event_swedenActionPerformed

    private void finlandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finlandActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Choosed Finland");
    }//GEN-LAST:event_finlandActionPerformed

    private void icelandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_icelandActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Choosed Iceland");
    }//GEN-LAST:event_icelandActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainmenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAbout;
    private javax.swing.JLabel btnCountries;
    private javax.swing.JButton btnDone;
    private javax.swing.JLabel btnHome;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnSignout;
    private javax.swing.JLabel btnVisit;
    private javax.swing.JComboBox<String> cmbTo;
    private javax.swing.JPanel countries;
    private javax.swing.JButton denmark;
    private javax.swing.JButton finland;
    private javax.swing.JPanel home;
    private javax.swing.JButton iceland;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton norway;
    private javax.swing.JButton sweden;
    private javax.swing.JTextField txtFrom;
    private javax.swing.JTextField txtFullname;
    private javax.swing.JTextArea txtOutput;
    private javax.swing.JPanel visit;
    // End of variables declaration//GEN-END:variables
}
